### PR TITLE
Try using env to test on multiple backends in travis

### PR DESCRIPTION
**Pull request by duncanparkes**
Don't merge yet, I'm just trying to test something on travis.

### CODE REVIEW

**Comment by duncanparkes** [comment]
This looks like it's worked - can you merge please? Then the next thing to do is stop all those tests failing: 1 on postgres and 45 errors on mysql!

**Comment by duncanparkes** [comment]
I just rebased this branch over master to get my latest test fix.

It's now at the stage where the tests pass on postgres about half the time. It would probably still be too annoying to have tests on mysql and postgres making pull requests fail travis randomly at the moment. If I squash a few more of the failures on postgres, then perhaps we can turn it on for postgres and then deal with mysql later.

**Comment by lfalvarez** [comment]
I tried to test them on MySQL and I'm getting this errors: 

* TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

* Incorrect string value: '\xD9\x83\xD9\x85\xD8\xA7...' for column 'subject' at row 1

**Comment by lfalvarez** [comment]
It is failing due to a problem with the way Django==1.6 handles tests and transactions, here I found something related to it: http://stackoverflow.com/questions/21458387/transactionmanagementerror-you-cant-execute-queries-until-the-end-of-the-atom

**Comment by duncanparkes** [comment]
It would be good to fix #350 in this branch.

**Comment by tmtmtmtm** [comment]
@duncanparkes What's the status of this one at the minute? Is it ready to go yet?

**Comment by lfalvarez** [comment]
Can I try to leave mysql out for now?

**Pull request closed without merging**
