### PR TITLE
Issues/724 adding a source should let you know if has already been linked

### PR DESCRIPTION
**Pull request by lfalvarez**
This lets you know that has been an error, when you try to relate a popit instance to a WriteIt that already has that popit instance related.

Here it is how it looks.

foto

It would probably need a bit of styling and wording any suggestions @tmtmtmtm @zarino ?

### CODE REVIEW

**Comment by lfalvarez** [comment]
It actually says something like ```You already have this popit instance related```

**Comment by tmtmtmtm** [comment]
Maybe "This PopIt was already previously added"?

**Comment by zarino** [comment]
Or "You are already pulling data from this PopIt"

Followed by… (feature creep!)… "But we are updating the database anyway, to pull in any new contacts" – since I have a feeling that, when people add a source, they probably "just want to get all the people from this popit into this writeit", and telling them the popit is already associated doesn't help them get people in.

(Feel free to throw the last paragraph out if there's something factually incorrect about how I assume the popit/writeit integration works)

**Comment by tmtmtmtm** [comment]
I started thinking through things like that (including whether we actually need to show an error at all, or just imply success, as the PopIt that they asked to be linked has been!) but quickly backed away again, as it seemed like a can of worms.

But if it's trivial to treat a re-adding of an existing popit as a request to re-fetch it, I'm all for doing that. 

@lfalvarez: if this is something that could be done in under 15 minutes, feel free to do it here. Otherwise let's just tweak the wording, and open a separate ticket for doing something better.

**Comment by lfalvarez** [comment]
So it isn't a very complex thing to do, but I'm wondering: Are we updating from a popit when someone said please create me a new one? if the answer to that is yes, please feel free to accept #826 that does exactly that.

**Comment by tmtmtmtm** [comment]
I've tweaked the wording in #826 — I suspect it should be merged into this Pull Request before doing anything further here!

**Comment by chrismytton** [comment]
Looks good! :+1:

**Pull request merged**
